### ISSUE TITLE
MEW issue

### ISSUE THREAD

**Issue by shrishtijain** [jvoisin/yara_rules#1]
Hi please help me out with the signatures created for mew

 for example  [MEW 10 by Northfox]

signature = 33 C0 E9 ?? ?? FF FF ?? 1C ?? ?? 40 

ep_only = true
  what does it means please reply 

Thanks & Regards

**Comment by jvoisin** [comment]
You might want to read [yara's documentation]( https://yara.readthedocs.io/en/v3.6.0/writingrules.html ) about how to write rules.
